keycloakx:
  fullnameOverride: keycloak
  command:
    - "/opt/keycloak/bin/kc.sh"
    - "start"
    - "--http-port=8080"
    - "--hostname-strict=false"
  extraEnv: |
    - name: KEYCLOAK_ADMIN
      value: admin
    - name: KEYCLOAK_ADMIN_PASSWORD
      value: admin
